apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: quickcommerce/product-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017"
            - name: DB_NAME
              value: "product_db"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
